# Trigger security scans in Checkmarx

name: Checkmarx Security Scan

on:
  push:
    branches: [master, main, develop]
    paths-ignore: 
      - '.github/**'
      - 'docs/**'
      - 'tools/**'
      - 'catalog-info.yaml'
      - 'README.md' 
  pull_request:
    paths-ignore: 
      - '.github/**'
      - 'docs/**'
      - 'tools/**'
      - 'catalog-info.yaml'
      - 'README.md' 
  workflow_dispatch:

jobs:
  ci:
    uses: unzercorp/js-tech-toolbox/.github/workflows/checkmarx-one-scan.yml@main
    secrets:
      inherit